/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;

import javax.swing.JOptionPane;
import modulos.Validaciones;


/**
 *
 * @author User
 */
public class pLogin extends javax.swing.JFrame {
    Validaciones _validaciones=new Validaciones();
    int xMouse,yMouse;
   
            /**
     * Creates new form pLogin
     */
    public pLogin() {
        initComponents();
        this.setSize(546,294);
        this.setLocationRelativeTo(null);
        jlogo.setIcon(_validaciones.getobtieneimagen("logo.png", jlogo.getWidth(),jlogo.getHeight()));
        jcerrar.setIcon(_validaciones.getobtieneimagen("iconCerrar.png", jcerrar.getWidth(), jcerrar.getHeight()));
        jicon1.setIcon(_validaciones.getobtieneimagen("iconcontrasena.png", jicon1.getWidth(), jicon1.getHeight()));
        jicon2.setIcon(_validaciones.getobtieneimagen("iconusuario.png", jicon2.getWidth(), jicon2.getHeight()));
        jlogo.requestFocus();
        jtxtcontrasena.setEchoChar((char)0);
        //carga el icono de la aplicacion 
        this.setIconImage(_validaciones.getImagenIconoProyecto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtusuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jtxtcontrasena = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jbtningresar = new javax.swing.JButton();
        jbarra = new javax.swing.JPanel();
        jcerrar = new javax.swing.JLabel();
        jicon1 = new javax.swing.JLabel();
        jicon2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesión");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtxtusuario.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 16)); // NOI18N
        jtxtusuario.setForeground(new java.awt.Color(204, 204, 204));
        jtxtusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtusuario.setText("Ingrese el nombre del usuario");
        jtxtusuario.setBorder(null);
        jtxtusuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtusuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtusuarioFocusLost(evt);
            }
        });
        jtxtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtusuarioKeyTyped(evt);
            }
        });

        jtxtcontrasena.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 16)); // NOI18N
        jtxtcontrasena.setForeground(new java.awt.Color(204, 204, 204));
        jtxtcontrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcontrasena.setText("Ingrese su contraseña");
        jtxtcontrasena.setBorder(null);
        jtxtcontrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcontrasenaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtcontrasenaFocusLost(evt);
            }
        });

        jbtningresar.setBackground(new java.awt.Color(153, 255, 255));
        jbtningresar.setFont(new java.awt.Font("Elephant", 0, 16)); // NOI18N
        jbtningresar.setForeground(new java.awt.Color(255, 255, 255));
        jbtningresar.setText("Ingresar");
        jbtningresar.setBorderPainted(false);
        jbtningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtningresarActionPerformed(evt);
            }
        });

        jbarra.setBackground(new java.awt.Color(255, 255, 255));
        jbarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbarraMouseDragged(evt);
            }
        });
        jbarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbarraMousePressed(evt);
            }
        });

        jcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jbarraLayout = new javax.swing.GroupLayout(jbarra);
        jbarra.setLayout(jbarraLayout);
        jbarraLayout.setHorizontalGroup(
            jbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbarraLayout.createSequentialGroup()
                .addComponent(jcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 520, Short.MAX_VALUE))
        );
        jbarraLayout.setVerticalGroup(
            jbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jicon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jicon1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jicon1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtcontrasena, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbtningresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jicon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtningresar)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 310, 290);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jlogo.setBackground(new java.awt.Color(0, 0, 128));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlogo, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(310, 0, 240, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcerrarMouseEntered
        jcerrar.setIcon(_validaciones.getobtieneimagen("iconCerrar2.png", jcerrar.getWidth(), jcerrar.getHeight()));
    }//GEN-LAST:event_jcerrarMouseEntered

    private void jcerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcerrarMouseExited
        jcerrar.setIcon(_validaciones.getobtieneimagen("iconCerrar.png", jcerrar.getWidth(), jcerrar.getHeight()));
    }//GEN-LAST:event_jcerrarMouseExited

    private void jcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcerrarMouseClicked
        System.exit(0);        
    }//GEN-LAST:event_jcerrarMouseClicked

    private void jbarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbarraMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jbarraMouseDragged

    private void jbarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbarraMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jbarraMousePressed

    private void jtxtusuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtusuarioFocusGained
        if(jtxtusuario.getText().equals("Ingrese el nombre del usuario")){
            jtxtusuario.setText("");
            jtxtusuario.setForeground(Color.BLACK);     
        }
    }//GEN-LAST:event_jtxtusuarioFocusGained

    private void jtxtusuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtusuarioFocusLost
        if (jtxtusuario.getText().equals("")) {
            jtxtusuario.setText("Ingrese el nombre del usuario");  
            jtxtusuario.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_jtxtusuarioFocusLost

    private void jbtningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtningresarActionPerformed
      String clave=new String(jtxtcontrasena.getPassword());
//        if (jtxtusuario.getText().equals("") || clave.equals("") ){
//            JOptionPane.showMessageDialog(this, "Existe información pendiente por ingresar...","ARECC",JOptionPane.INFORMATION_MESSAGE);
//        }else if (true)){//jtxtusuario.getText().trim().endsWith("erobles") && "erobles".trim().equals(String.valueOf(jtxtcontrasena.getPassword()))){
//            //pasar parametros a la clase
//            //JOptionPane.showMessageDialog(this, _data.getUsuario().getAlias()+" "+_data.getUsuario().getContrasena(),"ARECC",JOptionPane.INFORMATION_MESSAGE);
//            if(true){
//                
//            }else JOptionPane.showMessageDialog(this, "Error de usuario o contraseña. " + _data.getError(),"ARECC",JOptionPane.INFORMATION_MESSAGE);
//        }    
//        else JOptionPane.showMessageDialog(this, _data.getError(),"ARECC",JOptionPane.INFORMATION_MESSAGE);   
//     
    }//GEN-LAST:event_jbtningresarActionPerformed

    private void jicon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jicon1MousePressed
        jtxtcontrasena.setEchoChar((char)0);
        jtxtcontrasena.setForeground(Color.BLACK);
    }//GEN-LAST:event_jicon1MousePressed

    private void jicon1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jicon1MouseReleased
        jtxtcontrasena.setEchoChar('*');
    }//GEN-LAST:event_jicon1MouseReleased

    private void jtxtcontrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtcontrasenaFocusGained
        if("Ingrese su contraseña".trim().equals(String.valueOf(jtxtcontrasena.getPassword()))){
            jtxtcontrasena.setText("");
        jtxtcontrasena.setEchoChar('*');
        jtxtcontrasena.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jtxtcontrasenaFocusGained

    private void jtxtcontrasenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtcontrasenaFocusLost
       if (String.valueOf(jtxtcontrasena.getPassword()).equals("")) {
            jtxtcontrasena.setEchoChar((char)0);
           jtxtcontrasena.setText("Ingrese su contraseña");  
            jtxtcontrasena.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_jtxtcontrasenaFocusLost

    private void jtxtusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtusuarioKeyTyped
        if(_validaciones.GetSoloCaracter(evt)) evt.consume();        
    }//GEN-LAST:event_jtxtusuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jbarra;
    private javax.swing.JButton jbtningresar;
    private javax.swing.JLabel jcerrar;
    private javax.swing.JLabel jicon1;
    private javax.swing.JLabel jicon2;
    private javax.swing.JLabel jlogo;
    private javax.swing.JPasswordField jtxtcontrasena;
    private javax.swing.JTextField jtxtusuario;
    // End of variables declaration//GEN-END:variables
}
